#!/bin/bash

echo "---> Creating CPAN module bootstrap bundle"
perl -v

echo "---> Checking if you have OrePAN2"
cpanm OrePAN2

mkdir ./bootstrap

echo "---> Installing modules and its dependencies"
cpanm -L ./local --save-dists ./bootstrap/cache --notest $*

echo "---> Creating CPAN mirror out of cache"
orepan2-indexer ./bootstrap/cache

echo "---> Copying cpanm and bootstrap script"
ARGS="$*"
cp $(perldoc -l cpanm) ./bootstrap
cat ./bootstrap.sh | perl -nlpe "s/__ARGS__/$ARGS/" > ./bootstrap/bootstrap
chmod +x ./bootstrap/bootstrap

echo "---> All done!"
echo
echo "Copy bootstrap to remote, and run bootstrap command from there"
