#!/bin/bash

echo "---> Creating CPAN module bootstrap bundle"
perl -v

echo "---> Checking if you have OrePAN2"
cpanm OrePAN2

mkdir ./bundle

echo "---> Installing modules and its dependencies"
cpanm -L ./local --save-dists ./bundle/cache --notest $*

echo "---> Creating CPAN mirror out of cache"
orepan2-indexer ./bundle/cache

echo "---> Copying cpanm and bootstrap script"
ARGS="$*"
cp $(perldoc -l cpanm) ./bundle
cat ./bootstrap.sh | perl -nlpe "s/__ARGS__/$ARGS/" > ./bundle/bootstrap
chmod +x ./bundle/bootstrap

echo "---> All done!"
echo
echo "Copy bundle directory to remote, and run bootstrap command from there"
